# Generated by Django 3.0.4 on 2021-09-10 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertypost', '0002_propertymodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertymodel',
            name='category',
        ),
        migrations.AddField(
            model_name='propertymodel',
            name='evaluation',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], default=2, max_length=50),
            preserve_default=False,
        ),
    ]
