# Generated by Django 3.0.4 on 2021-09-11 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertypost', '0003_auto_20210910_0412'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertymodel',
            name='address',
            field=models.TextField(default='hukusima'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='propertymodel',
            name='evaluation',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=50),
        ),
    ]
