# Generated by Django 3.0.4 on 2021-09-19 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propertypost', '0004_auto_20210911_0245'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SampleModel',
        ),
    ]
