# Generated by Django 3.0.4 on 2021-09-19 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertypost', '0005_delete_samplemodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertymodel',
            old_name='title',
            new_name='property_name',
        ),
        migrations.AddField(
            model_name='propertymodel',
            name='school_name',
            field=models.CharField(default='会津大学', max_length=100),
            preserve_default=False,
        ),
    ]
